---
title: "Preparación"
author: "Julián Cruz, Ana Gómez"
output: html_document
---

```{r}
numerizar <- function(df, cuales){
  
  lapply(1:ncol(df), function(i){"if"(i %in% cuales, as.numeric(df[[i]]), as.character(df[[i]]))}) %>% data.frame(stringsAsFactors = FALSE) %>% setNames(names(df))
  
}

```



Este es el proceso de preparación de los datos

```{r}
library("tsne")
library("dplyr")
library("magrittr")
library("readxl")
library("maps")
library("rworldmap")

```


```{r}
filename <- "HDI_2014.xls"

downloaded.path <- file.path(getwd(), filename)

#origin <- "https://data.undp.org/api/views/5tuc-d2a9/rows.csv?accessType=DOWNLOAD"
origin <- "http://hdr.undp.org/sites/default/files/composite_tables/2015_Statistical_Annex_Table_1.xls"

if(!any(filename %in% dir())){curl_download(origin, downloaded.path)}

#HDI_2014 <- read.table(downloaded.path, sep = ",", dec = ".", header = TRUE, quote = "\"", na.strings = "..")

# Código quemado, falta estandarizar

downloaded.path %>% read_excel(sheet = 1, col_names = FALSE) -> HDI_2014_tmp

min(which(HDI_2014_tmp$X__1 == "1")) + 1 -> primera_fila

downloaded.path %>% read_excel(sheet = 1, skip = primera_fila, col_names = FALSE) -> HDI_2014_tmp

rows <- which(!is.na(HDI_2014_tmp$X__1))

# cols <- which(!is.na(HDI_2014_tmp[rows[1],]))

cols <- c(2, 3, 5, 7, 9, 11)

HDI_2014_tmp %>% "["(rows, cols) %>% numerizar(c(2:6)) %>% setNames( c("Nombre", 
              "IDH",
           "Expectativa_de_vida_al_nacer", 
           "Escolaridad_esperada", 
           "Escolaridad_media", 
           "GNI_per_capita")) -> HDI_2014
```

# Preparación

```{r}
normalization.rule <- function(x){
  Min <- min(x, na.rm = TRUE)
  Max <- max(x, na.rm = TRUE)
  "if"(Max == Min,1,(x-Min)/(Max - Min))
  }

world.map <- joinCountryData2Map(HDI_2014, joinCode = "NAME", nameJoinColumn = "Nombre")

world.map@data %$% data.frame(ISO3, ADMIN, Nombre, Expectativa_de_vida_al_nacer, Escolaridad_esperada, Escolaridad_media, GNI_per_capita) -> HDI_2014

# HDI_2014 %>% 
#   sapply(function(x){sum(is.na(x))}) %>% ">"(20) %>% not -> temp1

HDI_2014 %>% 
 apply(1, function(x){mean(is.na(x))<0.2}) -> temp1

HDI_2014 %>% 
sapply(is.numeric) -> temp2

# HDI_2014 %>% "["(temp1, temp2) %>% 
#   lapply(normalization.rule) %>% as.data.frame-> HDI_WORK

HDI_2014 %>% "["(temp1, temp2) -> HDI_WORK

HDI_2014 %>% filter(temp1) %$% ISO3 -> rownames(HDI_WORK)

HDI_2014 %>% filter(temp1) %$% data.frame(ISO3, ADMIN, Nombre) -> nombre_codigo

```

## Distancias

Obtenemos las distancias euclidianas entre países.

```{r, eval=FALSE}
HDI_WORK %>% dist %>% as.matrix -> dis_mat

dis_mat %>% as.data.frame %>% 
  mutate(nombre = as.character(nombre_codigo$Nombre), ADMIN = as.character(nombre_codigo$ADMIN)) -> distances

```

```{r mahalanobis}
HDI_WORK %>% cov -> covarianzas
HDI_WORK %>% apply(2, mean) -> medias

apply(HDI_WORK, 1, function(pais){mahalanobis(HDI_WORK, pais, covarianzas)}) -> dis_mat

dis_mat %>% log %>% as.data.frame %>% 
  mutate(nombre = as.character(nombre_codigo$Nombre), ADMIN = as.character(nombre_codigo$ADMIN)) -> distances

```

¿hacemos un tsne?

```{r, include = FALSE}

dis_mat %>% tsne %>% as.data.frame %>% set_colnames(c("xx", "yy")) -> tsne_paises

tsne_paises %>% plot


```

```{r}
save(list = ls(), file = "work_space.rda", envir = globalenv())

```
